services:
  - type: web
    name: academic-management-system
    env: python
    plan: free
    buildCommand: |-
      pip install -r requirements.txt
      export FLASK_APP=app.py
      flask db upgrade
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true 